export const cars = [
  { id: "car-01", title: "Toyota" },
  { id: "car-02", title: "Honda" },
  { id: "car-03", title: "Ford" },
  { id: "car-04", title: "Chevrolet" },
  { id: "car-05", title: "BMW" },
  { id: "car-06", title: "Mercedes-Benz" },
  { id: "car-07", title: "Audi" },
  { id: "car-08", title: "Volkswagen" },
  { id: "car-09", title: "Nissan" },
  { id: "car-10", title: "Hyundai" },
  { id: "car-11", title: "Kia" },
  { id: "car-12", title: "Subaru" },
  { id: "car-13", title: "Mazda" },
  { id: "car-14", title: "Lexus" },
  { id: "car-15", title: "Porsche" },
  { id: "car-16", title: "Jaguar" },
  { id: "car-17", title: "Land Rover" },
  { id: "car-18", title: "Chrysler" },
  { id: "car-19", title: "Buick" },
  { id: "car-20", title: "Cadillac" },
  { id: "car-21", title: "Tesla" },
  { id: "car-22", title: "Volvo" },
  { id: "car-23", title: "Acura" },
  { id: "car-24", title: "Infiniti" },
  { id: "car-25", title: "Alfa Romeo" },
  { id: "car-26", title: "Mitsubishi" },
  { id: "car-27", title: "Lincoln" },
  { id: "car-28", title: "GMC" },
  { id: "car-29", title: "Rivian" },
  { id: "car-30", title: "Polestar" },
];
