export const countries = [
  { id: "country-01", title: "United States 🇺🇸" },
  { id: "country-02", title: "Canada 🇨🇦" },
  { id: "country-03", title: "United Kingdom 🇬🇧" },
  { id: "country-04", title: "Germany 🇩🇪" },
  { id: "country-05", title: "France 🇫🇷" },
  { id: "country-06", title: "Italy 🇮🇹" },
  { id: "country-07", title: "Spain 🇪🇸" },
  { id: "country-08", title: "Australia 🇦🇺" },
  { id: "country-09", title: "Japan 🇯🇵" },
  { id: "country-10", title: "China 🇨🇳" },
  { id: "country-11", title: "India 🇮🇳" },
  { id: "country-12", title: "Brazil 🇧🇷" },
  { id: "country-13", title: "South Korea 🇰🇷" },
  { id: "country-14", title: "Mexico 🇲🇽" },
  { id: "country-15", title: "Russia 🇷🇺" },
  { id: "country-16", title: "South Africa 🇿🇦" },
  { id: "country-17", title: "Argentina 🇦🇷" },
  { id: "country-18", title: "Turkey 🇹🇷" },
  { id: "country-19", title: "Netherlands 🇳🇱" },
  { id: "country-20", title: "Saudi Arabia 🇸🇦" },
  { id: "country-21", title: "Sweden 🇸🇪" },
  { id: "country-22", title: "Norway 🇳🇴" },
  { id: "country-23", title: "Switzerland 🇨🇭" },
  { id: "country-24", title: "Belgium 🇧🇪" },
  { id: "country-25", title: "Egypt 🇪🇬" },
  { id: "country-26", title: "Thailand 🇹🇭" },
  { id: "country-27", title: "Malaysia 🇲🇾" },
  { id: "country-28", title: "Singapore 🇸🇬" },
  { id: "country-29", title: "United Arab Emirates 🇦🇪" },
  { id: "country-30", title: "Chile 🇨🇱" },
];
